import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { renderCatalog } from '../src/catalog.js';
import { CATALOG_FILENAME, rebuildCatalog } from '../src/catalog-store.js';
import { main } from '../src/cli.js';

/**
 * A transcript exactly as the writer produces one: seven keys, settled order,
 * `title`/`channel`/`duration` double-quoted.
 */
function transcript(overrides = {}) {
  const video = {
    title: 'A Talk',
    url: 'https://www.youtube.com/watch?v=o3CX_Y59_74',
    channel: 'freeCodeCamp.org',
    duration: '41:18',
    upload_date: '2026-09-10',
    fetched: '2026-09-16T14:03:05Z',
    subtitles: 'auto',
    ...overrides,
  };

  return [
    '---',
    `title: "${video.title}"`,
    `url: ${video.url}`,
    `channel: "${video.channel}"`,
    `duration: "${video.duration}"`,
    `upload_date: ${video.upload_date}`,
    `fetched: ${video.fetched}`,
    `subtitles: ${video.subtitles}`,
    '---',
    '',
    'Some prose.',
    '',
  ].join('\n');
}

/** Collects the lines main would have printed, so no test writes to a terminal. */
function capture() {
  const out = [];
  const err = [];
  return { out, err, io: { out: (line) => out.push(line), err: (line) => err.push(line) } };
}

/** A throwaway `transcripts/` directory: no test may touch the worktree's own. */
async function withDir(body) {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'yt-transcript-catalog-'));
  try {
    return await body(dir);
  } finally {
    await fs.rm(dir, { recursive: true, force: true });
  }
}

test('the catalog is a heading, a regeneration note and the five settled columns', () => {
  const { markdown, warnings } = renderCatalog([
    { path: 'a-talk.md', text: transcript() },
  ]);

  assert.deepEqual(warnings, []);
  assert.equal(
    markdown,
    [
      '# Transcripts',
      '',
      '1 transcripts, regenerated by yt-transcript catalog',
      '',
      '| Title | Channel | Duration | Uploaded | Subtitles |',
      '| --- | --- | --- | --- | --- |',
      '| [A Talk](a-talk.md) | freeCodeCamp.org | 41:18 | 2026-09-10 | auto |',
      '',
    ].join('\n'),
  );
});

test('rows sort by upload date descending, ties broken by title ascending', () => {
  const { markdown } = renderCatalog([
    { path: 'beta.md', text: transcript({ title: 'Beta', upload_date: '2026-01-02' }) },
    { path: 'older.md', text: transcript({ title: 'Older', upload_date: '2025-12-31' }) },
    { path: 'alpha.md', text: transcript({ title: 'Alpha', upload_date: '2026-01-02' }) },
    { path: 'newest.md', text: transcript({ title: 'Newest', upload_date: '2026-03-04' }) },
  ]);

  const titles = [...markdown.matchAll(/^\| \[([^\]]+)\]/gm)].map((match) => match[1]);
  assert.deepEqual(titles, ['Newest', 'Alpha', 'Beta', 'Older']);
});

test('a pipe in a title is escaped in the catalog cell only', () => {
  const text = transcript({ title: 'Rust | Go | C' });
  const { markdown } = renderCatalog([{ path: 'rust-go-c.md', text }]);

  assert.match(markdown, /\| \[Rust \\\| Go \\\| C\]\(rust-go-c\.md\) \|/);
  // The row still has exactly the five settled columns: the escape held.
  const row = markdown.split('\n').at(-2);
  assert.equal(row.split(/(?<!\\)\|/).length - 2, 5);
  // The frontmatter contract is untouched — the escape lives in the cell.
  assert.match(text, /^title: "Rust \| Go \| C"$/m);
});

test('zero transcripts yields the heading and the count line, and no table', () => {
  const { markdown, warnings } = renderCatalog([]);

  assert.deepEqual(warnings, []);
  assert.equal(
    markdown,
    ['# Transcripts', '', '0 transcripts, regenerated by yt-transcript catalog', ''].join('\n'),
  );
});

test('the catalog never lists itself, by the scan rule rather than by filename', () => {
  const readme = '# Transcripts\n\n1 transcripts, regenerated by yt-transcript catalog\n';
  const { markdown, warnings } = renderCatalog([
    { path: CATALOG_FILENAME, text: readme },
    { path: 'notes.md', text: '# Notes\n\nA file somebody dropped in here.\n' },
    { path: 'a-talk.md', text: transcript() },
  ]);

  // No frontmatter is not a malformed transcript — it is not a transcript.
  assert.deepEqual(warnings, []);
  assert.match(markdown, /^1 transcripts, /m);
  assert.doesNotMatch(markdown, /README/);
  assert.doesNotMatch(markdown, /notes\.md/);
});

test('a malformed transcript is named in a warning and skipped, the rest still written', () => {
  const truncated = '---\ntitle: "Cut Off"\nurl: https://www.youtube.com/watch?v=aaaaaaaaaaa\n';
  const incomplete = transcript({ title: 'Missing A Key' }).replace(/^channel: .*$/m, '');

  const { markdown, warnings } = renderCatalog([
    { path: 'cut-off.md', text: truncated },
    { path: 'missing-a-key.md', text: incomplete },
    { path: 'a-talk.md', text: transcript() },
  ]);

  assert.equal(warnings.length, 2);
  for (const [file, warning] of [
    ['cut-off.md', warnings[0]],
    ['missing-a-key.md', warnings[1]],
  ]) {
    assert.ok(warning.includes(file), `the warning does not name ${file}: ${warning}`);
    assert.match(warning, /re-download/i);
  }

  // One bad file must not cost the whole catalog.
  assert.match(markdown, /^1 transcripts, /m);
  assert.match(markdown, /\[A Talk\]\(a-talk\.md\)/);
});

test('CRLF frontmatter and a leading byte-order mark still read as a transcript', () => {
  const { markdown, warnings } = renderCatalog([
    { path: 'crlf.md', text: `﻿${transcript({ title: 'Windows' }).replace(/\n/g, '\r\n')}` },
  ]);

  assert.deepEqual(warnings, []);
  assert.match(markdown, /\[Windows\]\(crlf\.md\)/);
});

test('an escaped quote and backslash in a title survive the round trip', () => {
  const { markdown } = renderCatalog([
    { path: 'quoted.md', text: '---\ntitle: "He said \\"hi\\" \\\\ bye"\n'
      + 'url: https://www.youtube.com/watch?v=aaaaaaaaaaa\nchannel: "A"\nduration: "1:00"\n'
      + 'upload_date: 2026-01-01\nfetched: 2026-01-01T00:00:00Z\nsubtitles: manual\n---\n' },
  ]);

  assert.match(markdown, /\| \[He said "hi" \\ bye\]\(quoted\.md\) \| A \| 1:00 \| 2026-01-01 \| manual \|/);
});

test('a rebuild is a full rescan: a hand-deleted transcript loses exactly its row', async () => {
  await withDir(async (dir) => {
    await fs.writeFile(path.join(dir, 'a-talk.md'), transcript({ title: 'A Talk' }), 'utf8');
    await fs.writeFile(
      path.join(dir, 'b-talk.md'),
      transcript({ title: 'B Talk', upload_date: '2026-09-09' }),
      'utf8',
    );

    const first = await rebuildCatalog({ dir });
    assert.equal(first.count, 2);
    assert.deepEqual(first.warnings, []);

    await fs.rm(path.join(dir, 'b-talk.md'));
    const second = await rebuildCatalog({ dir });

    const markdown = await fs.readFile(path.join(dir, CATALOG_FILENAME), 'utf8');
    assert.equal(second.count, 1);
    assert.match(markdown, /\[A Talk\]/);
    assert.doesNotMatch(markdown, /B Talk/);
  });
});

test('rebuilding a directory that does not exist yet writes the empty catalog', async () => {
  await withDir(async (parent) => {
    const dir = path.join(parent, 'transcripts');

    const { count, file } = await rebuildCatalog({ dir });

    assert.equal(count, 0);
    assert.equal(await fs.readFile(file, 'utf8'), renderCatalog([]).markdown);
  });
});

test('`yt-transcript catalog` rebuilds without fetching anything', async () => {
  const { out, io } = capture();
  let rebuilds = 0;

  const code = await main(['catalog'], io, {
    preflight: async () => assert.fail('catalog preflighted yt-dlp'),
    fetchTranscript: async () => assert.fail('catalog fetched something'),
    rebuildCatalog: async () => {
      rebuilds += 1;
      return { file: 'transcripts/README.md', count: 3, warnings: [] };
    },
  });

  assert.equal(code, 0);
  assert.equal(rebuilds, 1);
  assert.match(out.join('\n'), /transcripts\/README\.md/);
  assert.match(out.join('\n'), /3 transcripts/);
});

test('catalog takes no target and no flags', async () => {
  const { err, io } = capture();

  assert.equal(await main(['catalog', 'o3CX_Y59_74'], io, { rebuildCatalog: async () => {} }), 1);
  assert.match(err.join('\n'), /Usage: yt-transcript/);
});

test('a successful single-video fetch rebuilds the catalog exactly once', async () => {
  const { io, err } = capture();
  let rebuilds = 0;

  const code = await main(['o3CX_Y59_74'], io, {
    preflight: async () => '2026.09.01',
    fetchTranscript: async () => ({
      file: 'transcripts/a-talk.md',
      transcript: { url: 'https://www.youtube.com/watch?v=o3CX_Y59_74', trackKind: 'auto' },
    }),
    rebuildCatalog: async () => {
      rebuilds += 1;
      return { file: 'transcripts/README.md', count: 1, warnings: ['a-bad-file.md is malformed'] };
    },
  });

  assert.equal(code, 0);
  assert.equal(rebuilds, 1);
  // A malformed neighbour is reported, never fatal.
  assert.match(err.join('\n'), /a-bad-file\.md/);
});

test('a failed fetch rebuilds nothing', async () => {
  const { io } = capture();

  const code = await main(['o3CX_Y59_74'], io, {
    preflight: async () => '2026.09.01',
    fetchTranscript: async () => {
      const { FetchError } = await import('../src/ytdlp.js');
      throw new FetchError('no subtitles', { url: 'x', exitCode: 0, failure: 'no-subtitles' });
    },
    rebuildCatalog: async () => assert.fail('a failed fetch rebuilt the catalog'),
  });

  assert.equal(code, 1);
});

test('a written transcript is still reported when the rebuild itself fails', async () => {
  const { out, err, io } = capture();

  const code = await main(['o3CX_Y59_74'], io, {
    preflight: async () => '2026.09.01',
    fetchTranscript: async () => ({
      file: 'transcripts/a-talk.md',
      transcript: { url: 'https://www.youtube.com/watch?v=o3CX_Y59_74', trackKind: 'auto' },
    }),
    rebuildCatalog: async () => {
      throw Object.assign(new Error('EACCES: permission denied'), { code: 'EACCES' });
    },
  });

  assert.equal(code, 1);
  assert.match(out.join('\n'), /transcripts\/a-talk\.md/);
  assert.match(err.join('\n'), /yt-transcript catalog/);
});
