import test from 'node:test';
import assert from 'node:assert/strict';

import { renderCatalog } from '../src/catalog.js';
import { renderFrontmatter } from '../src/frontmatter.js';

/**
 * A transcript exactly as the writer produces one: seven keys, settled order,
 * `title`/`channel`/`duration` double-quoted.
 */
function transcript(overrides = {}) {
  const video = {
    title: 'A Talk',
    url: 'https://www.youtube.com/watch?v=o3CX_Y59_74',
    channel: 'freeCodeCamp.org',
    duration: '41:18',
    upload_date: '2026-09-10',
    fetched: '2026-09-16T14:03:05Z',
    subtitles: 'auto',
    ...overrides,
  };

  return [
    '---',
    `title: "${video.title}"`,
    `url: ${video.url}`,
    `channel: "${video.channel}"`,
    `duration: "${video.duration}"`,
    `upload_date: ${video.upload_date}`,
    `fetched: ${video.fetched}`,
    `subtitles: ${video.subtitles}`,
    '---',
    '',
    'Some prose.',
    '',
  ].join('\n');
}

test('the catalog is a heading, a regeneration note and the five settled columns', () => {
  const { markdown, warnings } = renderCatalog([{ path: 'a-talk.md', text: transcript() }]);

  assert.deepEqual(warnings, []);
  assert.equal(
    markdown,
    [
      '# Transcripts',
      '',
      '1 transcripts, regenerated by yt-transcript catalog',
      '',
      '| Title | Channel | Duration | Uploaded | Subtitles |',
      '| --- | --- | --- | --- | --- |',
      '| [A Talk](a-talk.md) | freeCodeCamp.org | 41:18 | 2026-09-10 | auto |',
      '',
    ].join('\n'),
  );
});

test('rows sort by upload date descending, ties broken by title ascending', () => {
  const { markdown } = renderCatalog([
    { path: 'beta.md', text: transcript({ title: 'Beta', upload_date: '2026-01-02' }) },
    { path: 'older.md', text: transcript({ title: 'Older', upload_date: '2025-12-31' }) },
    { path: 'alpha.md', text: transcript({ title: 'Alpha', upload_date: '2026-01-02' }) },
    { path: 'newest.md', text: transcript({ title: 'Newest', upload_date: '2026-03-04' }) },
  ]);

  const titles = [...markdown.matchAll(/^\| \[([^\]]+)\]/gm)].map((match) => match[1]);
  assert.deepEqual(titles, ['Newest', 'Alpha', 'Beta', 'Older']);
});

test('a pipe in a title is escaped in the catalog cell only', () => {
  const text = transcript({ title: 'Rust | Go | C' });
  const { markdown } = renderCatalog([{ path: 'rust-go-c.md', text }]);

  assert.match(markdown, /\| \[Rust \\\| Go \\\| C\]\(rust-go-c\.md\) \|/);
  // The row still has exactly the five settled columns: the escape held.
  const row = markdown.split('\n').at(-2);
  assert.equal(row.split(/(?<!\\)\|/).length - 2, 5);
  // The frontmatter contract is untouched — the escape lives in the cell.
  assert.match(text, /^title: "Rust \| Go \| C"$/m);
});

test('zero transcripts yields the heading and the count line, and no table', () => {
  const { markdown, warnings } = renderCatalog([]);

  assert.deepEqual(warnings, []);
  assert.equal(
    markdown,
    ['# Transcripts', '', '0 transcripts, regenerated by yt-transcript catalog', ''].join('\n'),
  );
});

test('the catalog never lists itself, by the scan rule rather than by filename', () => {
  const { markdown, warnings } = renderCatalog([
    { path: 'README.md', text: '# Transcripts\n\n1 transcripts, regenerated by yt-transcript catalog\n' },
    { path: 'notes.md', text: '# Notes\n\nA file somebody dropped in here.\n' },
    { path: 'a-talk.md', text: transcript() },
  ]);

  // No frontmatter is not a malformed transcript — it is not a transcript.
  assert.deepEqual(warnings, []);
  assert.match(markdown, /^1 transcripts, /m);
  assert.doesNotMatch(markdown, /README/);
  assert.doesNotMatch(markdown, /notes\.md/);
});

test('a malformed transcript is named in a warning and skipped, the rest still written', () => {
  const truncated = '---\ntitle: "Cut Off"\nurl: https://www.youtube.com/watch?v=aaaaaaaaaaa\n';
  const incomplete = transcript({ title: 'Missing A Key' }).replace(/^channel: .*$/m, '');

  const { markdown, warnings } = renderCatalog([
    { path: 'cut-off.md', text: truncated },
    { path: 'missing-a-key.md', text: incomplete },
    { path: 'a-talk.md', text: transcript() },
  ]);

  assert.equal(warnings.length, 2);
  for (const [file, warning] of [
    ['cut-off.md', warnings[0]],
    ['missing-a-key.md', warnings[1]],
  ]) {
    assert.ok(warning.includes(file), `the warning does not name ${file}: ${warning}`);
    assert.match(warning, /re-download/i);
  }

  // One bad file must not cost the whole catalog.
  assert.match(markdown, /^1 transcripts, /m);
  assert.match(markdown, /\[A Talk\]\(a-talk\.md\)/);
});

test('CRLF frontmatter and a leading byte-order mark still read as a transcript', () => {
  const { markdown, warnings } = renderCatalog([
    { path: 'crlf.md', text: `﻿${transcript({ title: 'Windows' }).replace(/\n/g, '\r\n')}` },
  ]);

  assert.deepEqual(warnings, []);
  assert.match(markdown, /\[Windows\]\(crlf\.md\)/);
});

/**
 * The writer and this reader are two halves of one contract living in two
 * modules, so the escaping is pinned against `renderFrontmatter`'s real output
 * rather than against a hand-typed imitation of it.
 */
test('a title the writer had to escape survives the round trip into a cell', () => {
  const text = `${renderFrontmatter({
    title: '/wayfinder: Nothing | is "too" big \\ wide',
    url: 'https://www.youtube.com/watch?v=o3CX_Y59_74',
    channel: 'freeCodeCamp.org',
    duration: '41:18',
    uploadDate: '20260910',
    fetchedAt: new Date('2026-09-16T14:03:05.123Z'),
    subtitles: 'auto',
  })}\n\nProse.\n`;

  const { markdown, warnings } = renderCatalog([{ path: 'wayfinder.md', text }]);

  assert.deepEqual(warnings, []);
  assert.match(
    markdown,
    /\| \[\/wayfinder: Nothing \\\| is "too" big \\ wide\]\(wayfinder\.md\) \| freeCodeCamp\.org \| 41:18 \| 2026-09-10 \| auto \|/,
  );
});
