/**
 * The catalog: a Markdown table of every transcript on disk, derived wholly
 * from frontmatter so it cannot drift from what is actually there.
 *
 * This module is the seam — `(array of { path, text }) -> { markdown,
 * warnings }`. It takes **raw file text, not parsed frontmatter**, deliberately:
 * the scan rule and the malformed-file warning are the two things most worth
 * testing, and both live in the parse. Nothing here touches the filesystem;
 * `catalog-store.js` does the reading and the writing.
 *
 * **Derivability is the standing test for any future column**: computable from
 * the seven frontmatter keys plus the file path, or it does not belong. `url`
 * and `fetched` are deliberately not surfaced — `fetched` would churn a row on
 * every re-fetch.
 */

/** The five settled columns, in order. Each reads one frontmatter key. */
const COLUMNS = [
  { heading: 'Title', key: 'title' },
  { heading: 'Channel', key: 'channel' },
  { heading: 'Duration', key: 'duration' },
  { heading: 'Uploaded', key: 'upload_date' },
  { heading: 'Subtitles', key: 'subtitles' },
];

/**
 * The frontmatter contract is closed at exactly seven keys, so "incomplete"
 * has no other referent: a file missing one did not come from this tool, and
 * re-downloading it is the honest advice.
 */
const REQUIRED_KEYS = ['title', 'url', 'channel', 'duration', 'upload_date', 'fetched', 'subtitles'];

/**
 * Renders the catalog.
 *
 * @param {Array<{ path: string, text: string }>} files every `.md` in the
 *   transcripts directory, the catalog itself included — it is excluded by the
 *   scan rule below, with no filename special case.
 * @returns {{ markdown: string, warnings: string[], count: number }} the spec's
 *   seam names the two keys it covers, and every test exercises exactly those;
 *   `count` is the row count handed back rather than re-parsed out of the
 *   rendered note, so the two can never disagree.
 */
export function renderCatalog(files) {
  const rows = [];
  const warnings = [];

  for (const file of files) {
    const frontmatter = parseFrontmatter(file.text);

    // Three outcomes, and the middle one is the whole point of the scan rule:
    // no frontmatter block at all means "not a transcript", which is how the
    // catalog excludes itself. Only a file that *claims* to be a transcript
    // and then fails to be one earns a warning.
    if (frontmatter === null) continue;
    if (frontmatter.error) {
      warnings.push(`Skipped ${file.path}: ${frontmatter.error}. Re-download it to restore it.`);
      continue;
    }

    rows.push({ path: file.path, ...frontmatter.values });
  }

  // Both sort keys are immutable, so a re-fetch never reorders a row. Plain
  // string comparison, not `localeCompare`: `YYYY-MM-DD` orders correctly as
  // text, and code-unit order for the tie-break is reproducible everywhere.
  // Validation ran above, so no row here has a missing key to compare.
  rows.sort((a, b) => {
    if (a.upload_date !== b.upload_date) return a.upload_date < b.upload_date ? 1 : -1;
    if (a.title !== b.title) return a.title < b.title ? -1 : 1;
    // Two files sharing an upload date *and* a title is the true title
    // collision the store resolves by suffixing the filename. The spec leaves
    // their order open; settling it on the path keeps the generated file
    // identical across machines rather than following directory order.
    return a.path < b.path ? -1 : a.path > b.path ? 1 : 0;
  });

  const lines = [
    '# Transcripts',
    '',
    // Load-bearing: the file is derived, so anyone hand-editing it loses the
    // edit and the file must say so. Verbatim from the spec, plural always —
    // "1 transcripts" is the settled wording, not an oversight.
    `${rows.length} transcripts, regenerated by yt-transcript catalog`,
  ];

  if (rows.length > 0) {
    lines.push(
      '',
      `| ${COLUMNS.map((column) => column.heading).join(' | ')} |`,
      `| ${COLUMNS.map(() => '---').join(' | ')} |`,
      ...rows.map(renderRow),
    );
  }

  return { markdown: `${lines.join('\n')}\n`, warnings, count: rows.length };
}

/**
 * The `url`s of every transcript in a set of files — a batch's skip set.
 *
 * Deliberately the **same scan** the catalog rebuild performs, sharing its
 * parse rather than walking the directory a third way: two scan rules that
 * could disagree about what a transcript is would let a batch re-fetch a video
 * the catalog already lists.
 *
 * Matching is on the frontmatter `url`, never the filename, so a transcript
 * renamed by hand is still recognised. A malformed file contributes no url and
 * no warning here — it is re-fetched, which is what the catalog's warning tells
 * the user to do anyway.
 *
 * @param {Array<{ path: string, text: string }>} files
 * @returns {string[]}
 */
export function scanTranscriptUrls(files) {
  const urls = [];
  for (const file of files) {
    const frontmatter = parseFrontmatter(file.text);
    if (frontmatter === null || frontmatter.error) continue;
    urls.push(frontmatter.values.url);
  }
  return urls;
}

function renderRow(row) {
  const cells = COLUMNS.map((column) =>
    column.key === 'title' ? `[${cell(row.title)}](${row.path})` : cell(row[column.key]),
  );
  return `| ${cells.join(' | ')} |`;
}

/**
 * A `|` is escaped as `\|` **in the catalog cell only** — the frontmatter and
 * filename contracts are untouched. Applied to every cell rather than to the
 * title alone: an unescaped pipe anywhere breaks the table structurally, and a
 * channel name may carry one just as a title may.
 */
function cell(value) {
  return String(value).replace(/\|/g, '\\|');
}

/**
 * Reads a transcript's frontmatter block.
 *
 * Line-oriented rather than a regex per key, so CRLF costs nothing and the
 * fixtures' line endings are never normalised.
 *
 * Structure is strict and values are lenient: the writer enforces the value
 * formats, and the catalog's job is to report what is on disk, not to re-judge
 * it.
 *
 * @returns {null | { error: string } | { values: Record<string, string> }}
 *   `null` when the file is not a transcript at all.
 */
function parseFrontmatter(text) {
  // A byte-order mark is not a reason to drop a transcript from its own
  // catalog, and the failure mode without this is a silent skip.
  const lines = String(text).replace(/^\uFEFF/, '').split(/\r?\n/);

  if (lines[0]?.trim() !== '---') return null;

  const closing = lines.indexOf('---', 1);
  // Opened and never closed: this file claims to be a transcript, so it is a
  // malformed one rather than something else entirely.
  if (closing === -1) return { error: 'its frontmatter block is never closed' };

  const values = {};
  for (const line of lines.slice(1, closing)) {
    if (line.trim() === '') continue;
    const match = /^([A-Za-z_][A-Za-z0-9_]*):[ \t]*(.*)$/.exec(line);
    if (!match) return { error: 'its frontmatter is not readable' };
    values[match[1]] = unquote(match[2].trim());
  }

  const missing = REQUIRED_KEYS.filter((key) => !(key in values));
  if (missing.length > 0) {
    return { error: `its frontmatter is missing ${missing.join(', ')}` };
  }

  return { values };
}

/**
 * The inverse of the writer's unconditional double-quoting. One pass over the
 * escapes, not two: sequential `\"` then `\\` replacements mis-handle `\\"`.
 */
function unquote(value) {
  const quoted = /^"([\s\S]*)"$/.exec(value);
  return quoted ? quoted[1].replace(/\\(["\\])/g, '$1') : value;
}
